// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// ResourceMetrics is a collection of metrics from a Resource.
type LazyResourceMetrics struct {
	Resource               Resource
	ScopeMetrics           [][]byte
	SchemaUrl              string
	DeprecatedScopeMetrics []ScopeMetrics
}

var (
	protoPoolLazyResourceMetrics = sync.Pool{
		New: func() any {
			return &LazyResourceMetrics{}
		},
	}
)

func NewLazyResourceMetrics() *LazyResourceMetrics {
	if !UseProtoPooling.IsEnabled() {
		return &LazyResourceMetrics{}
	}
	return protoPoolLazyResourceMetrics.Get().(*LazyResourceMetrics)
}

func DeleteLazyResourceMetrics(orig *LazyResourceMetrics, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	DeleteResource(&orig.Resource, false)
	for i := range orig.DeprecatedScopeMetrics {
		DeleteScopeMetrics(&orig.DeprecatedScopeMetrics[i], false)
	}

	orig.Reset()
	if nullable {
		protoPoolLazyResourceMetrics.Put(orig)
	}
}

func CopyLazyResourceMetrics(dest, src *LazyResourceMetrics) *LazyResourceMetrics {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewLazyResourceMetrics()
	}
	CopyResource(&dest.Resource, &src.Resource)

	dest.ScopeMetrics = append(dest.ScopeMetrics[:0], src.ScopeMetrics...)
	dest.SchemaUrl = src.SchemaUrl

	dest.DeprecatedScopeMetrics = CopyScopeMetricsSlice(dest.DeprecatedScopeMetrics, src.DeprecatedScopeMetrics)

	return dest
}

func CopyLazyResourceMetricsSlice(dest, src []LazyResourceMetrics) []LazyResourceMetrics {
	var newDest []LazyResourceMetrics
	if cap(dest) < len(src) {
		newDest = make([]LazyResourceMetrics, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteLazyResourceMetrics(&dest[i], false)
		}
	}
	for i := range src {
		CopyLazyResourceMetrics(&newDest[i], &src[i])
	}
	return newDest
}

func CopyLazyResourceMetricsPtrSlice(dest, src []*LazyResourceMetrics) []*LazyResourceMetrics {
	var newDest []*LazyResourceMetrics
	if cap(dest) < len(src) {
		newDest = make([]*LazyResourceMetrics, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewLazyResourceMetrics()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteLazyResourceMetrics(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewLazyResourceMetrics()
		}
	}
	for i := range src {
		CopyLazyResourceMetrics(newDest[i], src[i])
	}
	return newDest
}

func (orig *LazyResourceMetrics) Reset() {
	*orig = LazyResourceMetrics{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *LazyResourceMetrics) MarshalJSON(dest *json.Stream) {
	dest.WriteObjectStart()
	dest.WriteObjectField("resource")
	orig.Resource.MarshalJSON(dest)
	if len(orig.ScopeMetrics) > 0 {
		dest.WriteObjectField("scopeMetrics")
		dest.WriteArrayStart()
		dest.WriteBytes(orig.ScopeMetrics[0])
		for i := 1; i < len(orig.ScopeMetrics); i++ {
			dest.WriteMore()
			dest.WriteBytes(orig.ScopeMetrics[i])
		}
		dest.WriteArrayEnd()
	}
	if orig.SchemaUrl != "" {
		dest.WriteObjectField("schemaUrl")
		dest.WriteString(orig.SchemaUrl)
	}
	if len(orig.DeprecatedScopeMetrics) > 0 {
		dest.WriteObjectField("deprecatedScopeMetrics")
		dest.WriteArrayStart()
		orig.DeprecatedScopeMetrics[0].MarshalJSON(dest)
		for i := 1; i < len(orig.DeprecatedScopeMetrics); i++ {
			dest.WriteMore()
			orig.DeprecatedScopeMetrics[i].MarshalJSON(dest)
		}
		dest.WriteArrayEnd()
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *LazyResourceMetrics) UnmarshalJSON(iter *json.Iterator) {
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "resource":

			orig.Resource.UnmarshalJSON(iter)
		case "scopeMetrics", "scope_metrics":
			for iter.ReadArray() {
				orig.ScopeMetrics = append(orig.ScopeMetrics, iter.ReadBytes())
			}

		case "schemaUrl", "schema_url":
			orig.SchemaUrl = iter.ReadString()
		case "deprecatedScopeMetrics", "deprecated_scope_metrics":
			for iter.ReadArray() {
				orig.DeprecatedScopeMetrics = append(orig.DeprecatedScopeMetrics, ScopeMetrics{})
				orig.DeprecatedScopeMetrics[len(orig.DeprecatedScopeMetrics)-1].UnmarshalJSON(iter)
			}

		default:
			iter.Skip()
		}
	}
}

func (orig *LazyResourceMetrics) SizeProto() int {
	var n int
	var l int
	_ = l
	l = orig.Resource.SizeProto()
	n += 1 + proto.Sov(uint64(l)) + l
	for _, s := range orig.ScopeMetrics {
		l = len(s)
		n += 1 + proto.Sov(uint64(l)) + l
	}
	l = len(orig.SchemaUrl)
	if l > 0 {
		n += 1 + proto.Sov(uint64(l)) + l
	}
	for i := range orig.DeprecatedScopeMetrics {
		l = orig.DeprecatedScopeMetrics[i].SizeProto()
		n += 2 + proto.Sov(uint64(l)) + l
	}
	return n
}

func (orig *LazyResourceMetrics) MarshalProto(buf []byte) int {
	pos := len(buf)
	var l int
	_ = l
	l = orig.Resource.MarshalProto(buf[:pos])
	pos -= l
	pos = proto.EncodeVarint(buf, pos, uint64(l))
	pos--
	buf[pos] = 0xa

	for i := len(orig.ScopeMetrics) - 1; i >= 0; i-- {
		l = len(orig.ScopeMetrics[i])
		pos -= l
		copy(buf[pos:], orig.ScopeMetrics[i])
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x12
	}
	l = len(orig.SchemaUrl)
	if l > 0 {
		pos -= l
		copy(buf[pos:], orig.SchemaUrl)
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x1a
	}
	for i := len(orig.DeprecatedScopeMetrics) - 1; i >= 0; i-- {
		l = orig.DeprecatedScopeMetrics[i].MarshalProto(buf[:pos])
		pos -= l
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0x3e
		pos--
		buf[pos] = 0xc2
	}
	return len(buf) - pos
}

func (orig *LazyResourceMetrics) UnmarshalProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		// If in a group parsing, move to the next tag.
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field Resource", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length

			err = orig.Resource.UnmarshalProto(buf[startPos:pos])
			if err != nil {
				return err
			}

		case 2:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ScopeMetrics", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			if length != 0 {
				orig.ScopeMetrics = append(orig.ScopeMetrics, buf[startPos:pos])
			} else {
				orig.ScopeMetrics = append(orig.ScopeMetrics, nil)
			}

		case 3:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field SchemaUrl", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.SchemaUrl = proto.YoloString(buf[startPos:pos])

		case 1000:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field DeprecatedScopeMetrics", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			orig.DeprecatedScopeMetrics = append(orig.DeprecatedScopeMetrics, ScopeMetrics{})
			err = orig.DeprecatedScopeMetrics[len(orig.DeprecatedScopeMetrics)-1].UnmarshalProto(buf[startPos:pos])
			if err != nil {
				return err
			}
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestLazyResourceMetrics() *LazyResourceMetrics {
	orig := NewLazyResourceMetrics()
	orig.Resource = *GenTestResource()
	orig.ScopeMetrics = [][]byte{nil, {1, 2, 3}}
	orig.SchemaUrl = "test_schemaurl"
	orig.DeprecatedScopeMetrics = []ScopeMetrics{{}, *GenTestScopeMetrics()}
	return orig
}

func GenTestLazyResourceMetricsPtrSlice() []*LazyResourceMetrics {
	orig := make([]*LazyResourceMetrics, 5)
	orig[0] = NewLazyResourceMetrics()
	orig[1] = GenTestLazyResourceMetrics()
	orig[2] = NewLazyResourceMetrics()
	orig[3] = GenTestLazyResourceMetrics()
	orig[4] = NewLazyResourceMetrics()
	return orig
}

func GenTestLazyResourceMetricsSlice() []LazyResourceMetrics {
	orig := make([]LazyResourceMetrics, 5)
	orig[1] = *GenTestLazyResourceMetrics()
	orig[3] = *GenTestLazyResourceMetrics()
	return orig
}
