// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"strconv"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	gootlpmetrics "go.opentelemetry.io/proto/slim/otlp/metrics/v1"
	"google.golang.org/protobuf/proto"

	"go.opentelemetry.io/collector/featuregate"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

func TestCopyLazyResourceMetrics(t *testing.T) {
	for name, src := range genTestEncodingValuesLazyResourceMetrics() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				dest := NewLazyResourceMetrics()
				CopyLazyResourceMetrics(dest, src)
				assert.Equal(t, src, dest)
				CopyLazyResourceMetrics(dest, dest)
				assert.Equal(t, src, dest)
			})
		}
	}
}

func TestCopyLazyResourceMetricsSlice(t *testing.T) {
	src := []LazyResourceMetrics{}
	dest := []LazyResourceMetrics{}
	// Test CopyTo empty
	dest = CopyLazyResourceMetricsSlice(dest, src)
	assert.Equal(t, []LazyResourceMetrics{}, dest)

	// Test CopyTo larger slice
	src = GenTestLazyResourceMetricsSlice()
	dest = CopyLazyResourceMetricsSlice(dest, src)
	assert.Equal(t, GenTestLazyResourceMetricsSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyLazyResourceMetricsSlice(dest, src)
	assert.Equal(t, GenTestLazyResourceMetricsSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyLazyResourceMetricsSlice(dest, []LazyResourceMetrics{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyLazyResourceMetricsSlice(dest, src)
	assert.Equal(t, GenTestLazyResourceMetricsSlice(), dest)
}

func TestCopyLazyResourceMetricsPtrSlice(t *testing.T) {
	src := []*LazyResourceMetrics{}
	dest := []*LazyResourceMetrics{}
	// Test CopyTo empty
	dest = CopyLazyResourceMetricsPtrSlice(dest, src)
	assert.Equal(t, []*LazyResourceMetrics{}, dest)

	// Test CopyTo larger slice
	src = GenTestLazyResourceMetricsPtrSlice()
	dest = CopyLazyResourceMetricsPtrSlice(dest, src)
	assert.Equal(t, GenTestLazyResourceMetricsPtrSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyLazyResourceMetricsPtrSlice(dest, src)
	assert.Equal(t, GenTestLazyResourceMetricsPtrSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyLazyResourceMetricsPtrSlice(dest, []*LazyResourceMetrics{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyLazyResourceMetricsPtrSlice(dest, src)
	assert.Equal(t, GenTestLazyResourceMetricsPtrSlice(), dest)
}

func TestMarshalAndUnmarshalJSONLazyResourceMetricsUnknown(t *testing.T) {
	iter := json.BorrowIterator([]byte(`{"unknown": "string"}`))
	defer json.ReturnIterator(iter)
	dest := NewLazyResourceMetrics()
	dest.UnmarshalJSON(iter)
	require.NoError(t, iter.Error())
	assert.Equal(t, NewLazyResourceMetrics(), dest)
}

func TestMarshalAndUnmarshalJSONLazyResourceMetrics(t *testing.T) {
	for name, src := range genTestEncodingValuesLazyResourceMetrics() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				stream := json.BorrowStream(nil)
				defer json.ReturnStream(stream)
				src.MarshalJSON(stream)
				require.NoError(t, stream.Error())

				iter := json.BorrowIterator(stream.Buffer())
				defer json.ReturnIterator(iter)
				dest := NewLazyResourceMetrics()
				dest.UnmarshalJSON(iter)
				require.NoError(t, iter.Error())

				assert.Equal(t, src, dest)
				DeleteLazyResourceMetrics(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoLazyResourceMetricsFailing(t *testing.T) {
	for name, buf := range genTestFailingUnmarshalProtoValuesLazyResourceMetrics() {
		t.Run(name, func(t *testing.T) {
			dest := NewLazyResourceMetrics()
			require.Error(t, dest.UnmarshalProto(buf))
		})
	}
}

func TestMarshalAndUnmarshalProtoLazyResourceMetricsUnknown(t *testing.T) {
	dest := NewLazyResourceMetrics()
	// message Test { required int64 field = 1313; } encoding { "field": "1234" }
	require.NoError(t, dest.UnmarshalProto([]byte{0x88, 0x52, 0xD2, 0x09}))
	assert.Equal(t, NewLazyResourceMetrics(), dest)
}

func TestMarshalAndUnmarshalProtoLazyResourceMetrics(t *testing.T) {
	for name, src := range genTestEncodingValuesLazyResourceMetrics() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				buf := make([]byte, src.SizeProto())
				gotSize := src.MarshalProto(buf)
				assert.Equal(t, len(buf), gotSize)

				dest := NewLazyResourceMetrics()
				require.NoError(t, dest.UnmarshalProto(buf))

				assert.Equal(t, src, dest)
				DeleteLazyResourceMetrics(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoViaProtobufLazyResourceMetrics(t *testing.T) {
	for name, src := range genTestEncodingValuesLazyResourceMetrics() {
		t.Run(name, func(t *testing.T) {
			buf := make([]byte, src.SizeProto())
			gotSize := src.MarshalProto(buf)
			assert.Equal(t, len(buf), gotSize)

			goDest := &gootlpmetrics.LazyResourceMetrics{}
			require.NoError(t, proto.Unmarshal(buf, goDest))

			goBuf, err := proto.Marshal(goDest)
			require.NoError(t, err)

			dest := NewLazyResourceMetrics()
			require.NoError(t, dest.UnmarshalProto(goBuf))
			assert.Equal(t, src, dest)
		})
	}
}

func genTestFailingUnmarshalProtoValuesLazyResourceMetrics() map[string][]byte {
	return map[string][]byte{
		"invalid_field":                          {0x02},
		"Resource/wrong_wire_type":               {0xc},
		"Resource/missing_value":                 {0xa},
		"ScopeMetrics/wrong_wire_type":           {0x14},
		"ScopeMetrics/missing_value":             {0x12},
		"SchemaUrl/wrong_wire_type":              {0x1c},
		"SchemaUrl/missing_value":                {0x1a},
		"DeprecatedScopeMetrics/wrong_wire_type": {0xc4, 0x3e},
		"DeprecatedScopeMetrics/missing_value":   {0xc2, 0x3e},
	}
}

func genTestEncodingValuesLazyResourceMetrics() map[string]*LazyResourceMetrics {
	return map[string]*LazyResourceMetrics{
		"empty":                       NewLazyResourceMetrics(),
		"Resource/test":               {Resource: *GenTestResource()},
		"ScopeMetrics/test":           {ScopeMetrics: [][]byte{nil, {1, 2, 3}}},
		"SchemaUrl/test":              {SchemaUrl: "test_schemaurl"},
		"DeprecatedScopeMetrics/test": {DeprecatedScopeMetrics: []ScopeMetrics{{}, *GenTestScopeMetrics()}},
	}
}
