// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

type BytesSliceWrapper struct {
	orig  *[][]byte
	state *State
}

func GetBytesSliceOrig(ms BytesSliceWrapper) *[][]byte {
	return ms.orig
}

func GetBytesSliceState(ms BytesSliceWrapper) *State {
	return ms.state
}

func NewBytesSliceWrapper(orig *[][]byte, state *State) BytesSliceWrapper {
	return BytesSliceWrapper{orig: orig, state: state}
}

func GenTestBytesSliceWrapper() BytesSliceWrapper {
	orig := [][]byte{{1}, {2}, {3}}
	return NewBytesSliceWrapper(&orig, NewState())
}

func GenTestBytesSlice() [][]byte {
	return [][]byte{{1}, {2}, {3}}
}
