// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"fmt"
	"sync"

	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/internal/proto"
)

// LazyMetrics is the top-level struct that is propagated through the metrics pipeline.
// Use NewLazyMetrics to create new instance, zero-initialized instance is not valid for use.
type LazyExportMetricsServiceRequest struct {
	ResourceMetrics [][]byte
}

var (
	protoPoolLazyExportMetricsServiceRequest = sync.Pool{
		New: func() any {
			return &LazyExportMetricsServiceRequest{}
		},
	}
)

func NewLazyExportMetricsServiceRequest() *LazyExportMetricsServiceRequest {
	if !UseProtoPooling.IsEnabled() {
		return &LazyExportMetricsServiceRequest{}
	}
	return protoPoolLazyExportMetricsServiceRequest.Get().(*LazyExportMetricsServiceRequest)
}

func DeleteLazyExportMetricsServiceRequest(orig *LazyExportMetricsServiceRequest, nullable bool) {
	if orig == nil {
		return
	}

	if !UseProtoPooling.IsEnabled() {
		orig.Reset()
		return
	}

	orig.Reset()
	if nullable {
		protoPoolLazyExportMetricsServiceRequest.Put(orig)
	}
}

func CopyLazyExportMetricsServiceRequest(dest, src *LazyExportMetricsServiceRequest) *LazyExportMetricsServiceRequest {
	// If copying to same object, just return.
	if src == dest {
		return dest
	}

	if src == nil {
		return nil
	}

	if dest == nil {
		dest = NewLazyExportMetricsServiceRequest()
	}
	dest.ResourceMetrics = append(dest.ResourceMetrics[:0], src.ResourceMetrics...)

	return dest
}

func CopyLazyExportMetricsServiceRequestSlice(dest, src []LazyExportMetricsServiceRequest) []LazyExportMetricsServiceRequest {
	var newDest []LazyExportMetricsServiceRequest
	if cap(dest) < len(src) {
		newDest = make([]LazyExportMetricsServiceRequest, len(src))
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteLazyExportMetricsServiceRequest(&dest[i], false)
		}
	}
	for i := range src {
		CopyLazyExportMetricsServiceRequest(&newDest[i], &src[i])
	}
	return newDest
}

func CopyLazyExportMetricsServiceRequestPtrSlice(dest, src []*LazyExportMetricsServiceRequest) []*LazyExportMetricsServiceRequest {
	var newDest []*LazyExportMetricsServiceRequest
	if cap(dest) < len(src) {
		newDest = make([]*LazyExportMetricsServiceRequest, len(src))
		// Copy old pointers to re-use.
		copy(newDest, dest)
		// Add new pointers for missing elements from len(dest) to len(srt).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewLazyExportMetricsServiceRequest()
		}
	} else {
		newDest = dest[:len(src)]
		// Cleanup the rest of the elements so GC can free the memory.
		// This can happen when len(src) < len(dest) < cap(dest).
		for i := len(src); i < len(dest); i++ {
			DeleteLazyExportMetricsServiceRequest(dest[i], true)
			dest[i] = nil
		}
		// Add new pointers for missing elements.
		// This can happen when len(dest) < len(src) < cap(dest).
		for i := len(dest); i < len(src); i++ {
			newDest[i] = NewLazyExportMetricsServiceRequest()
		}
	}
	for i := range src {
		CopyLazyExportMetricsServiceRequest(newDest[i], src[i])
	}
	return newDest
}

func (orig *LazyExportMetricsServiceRequest) Reset() {
	*orig = LazyExportMetricsServiceRequest{}
}

// MarshalJSON marshals all properties from the current struct to the destination stream.
func (orig *LazyExportMetricsServiceRequest) MarshalJSON(dest *json.Stream) {
	dest.WriteObjectStart()
	if len(orig.ResourceMetrics) > 0 {
		dest.WriteObjectField("resourceMetrics")
		dest.WriteArrayStart()
		dest.WriteBytes(orig.ResourceMetrics[0])
		for i := 1; i < len(orig.ResourceMetrics); i++ {
			dest.WriteMore()
			dest.WriteBytes(orig.ResourceMetrics[i])
		}
		dest.WriteArrayEnd()
	}
	dest.WriteObjectEnd()
}

// UnmarshalJSON unmarshals all properties from the current struct from the source iterator.
func (orig *LazyExportMetricsServiceRequest) UnmarshalJSON(iter *json.Iterator) {
	for f := iter.ReadObject(); f != ""; f = iter.ReadObject() {
		switch f {
		case "resourceMetrics", "resource_metrics":
			for iter.ReadArray() {
				orig.ResourceMetrics = append(orig.ResourceMetrics, iter.ReadBytes())
			}

		default:
			iter.Skip()
		}
	}
}

func (orig *LazyExportMetricsServiceRequest) SizeProto() int {
	var n int
	var l int
	_ = l
	for _, s := range orig.ResourceMetrics {
		l = len(s)
		n += 1 + proto.Sov(uint64(l)) + l
	}
	return n
}

func (orig *LazyExportMetricsServiceRequest) MarshalProto(buf []byte) int {
	pos := len(buf)
	var l int
	_ = l
	for i := len(orig.ResourceMetrics) - 1; i >= 0; i-- {
		l = len(orig.ResourceMetrics[i])
		pos -= l
		copy(buf[pos:], orig.ResourceMetrics[i])
		pos = proto.EncodeVarint(buf, pos, uint64(l))
		pos--
		buf[pos] = 0xa
	}
	return len(buf) - pos
}

func (orig *LazyExportMetricsServiceRequest) UnmarshalProto(buf []byte) error {
	var err error
	var fieldNum int32
	var wireType proto.WireType

	l := len(buf)
	pos := 0
	for pos < l {
		// If in a group parsing, move to the next tag.
		fieldNum, wireType, pos, err = proto.ConsumeTag(buf, pos)
		if err != nil {
			return err
		}
		switch fieldNum {

		case 1:
			if wireType != proto.WireTypeLen {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceMetrics", wireType)
			}
			var length int
			length, pos, err = proto.ConsumeLen(buf, pos)
			if err != nil {
				return err
			}
			startPos := pos - length
			if length != 0 {
				orig.ResourceMetrics = append(orig.ResourceMetrics, buf[startPos:pos])
			} else {
				orig.ResourceMetrics = append(orig.ResourceMetrics, nil)
			}
		default:
			pos, err = proto.ConsumeUnknown(buf, pos, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func GenTestLazyExportMetricsServiceRequest() *LazyExportMetricsServiceRequest {
	orig := NewLazyExportMetricsServiceRequest()
	orig.ResourceMetrics = [][]byte{nil, {1, 2, 3}}
	return orig
}

func GenTestLazyExportMetricsServiceRequestPtrSlice() []*LazyExportMetricsServiceRequest {
	orig := make([]*LazyExportMetricsServiceRequest, 5)
	orig[0] = NewLazyExportMetricsServiceRequest()
	orig[1] = GenTestLazyExportMetricsServiceRequest()
	orig[2] = NewLazyExportMetricsServiceRequest()
	orig[3] = GenTestLazyExportMetricsServiceRequest()
	orig[4] = NewLazyExportMetricsServiceRequest()
	return orig
}

func GenTestLazyExportMetricsServiceRequestSlice() []LazyExportMetricsServiceRequest {
	orig := make([]LazyExportMetricsServiceRequest, 5)
	orig[1] = *GenTestLazyExportMetricsServiceRequest()
	orig[3] = *GenTestLazyExportMetricsServiceRequest()
	return orig
}
