// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

import (
	"strconv"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	gootlpcollectormetrics "go.opentelemetry.io/proto/slim/otlp/collector/metrics/v1"
	"google.golang.org/protobuf/proto"

	"go.opentelemetry.io/collector/featuregate"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

func TestCopyLazyExportMetricsServiceRequest(t *testing.T) {
	for name, src := range genTestEncodingValuesLazyExportMetricsServiceRequest() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				dest := NewLazyExportMetricsServiceRequest()
				CopyLazyExportMetricsServiceRequest(dest, src)
				assert.Equal(t, src, dest)
				CopyLazyExportMetricsServiceRequest(dest, dest)
				assert.Equal(t, src, dest)
			})
		}
	}
}

func TestCopyLazyExportMetricsServiceRequestSlice(t *testing.T) {
	src := []LazyExportMetricsServiceRequest{}
	dest := []LazyExportMetricsServiceRequest{}
	// Test CopyTo empty
	dest = CopyLazyExportMetricsServiceRequestSlice(dest, src)
	assert.Equal(t, []LazyExportMetricsServiceRequest{}, dest)

	// Test CopyTo larger slice
	src = GenTestLazyExportMetricsServiceRequestSlice()
	dest = CopyLazyExportMetricsServiceRequestSlice(dest, src)
	assert.Equal(t, GenTestLazyExportMetricsServiceRequestSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyLazyExportMetricsServiceRequestSlice(dest, src)
	assert.Equal(t, GenTestLazyExportMetricsServiceRequestSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyLazyExportMetricsServiceRequestSlice(dest, []LazyExportMetricsServiceRequest{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyLazyExportMetricsServiceRequestSlice(dest, src)
	assert.Equal(t, GenTestLazyExportMetricsServiceRequestSlice(), dest)
}

func TestCopyLazyExportMetricsServiceRequestPtrSlice(t *testing.T) {
	src := []*LazyExportMetricsServiceRequest{}
	dest := []*LazyExportMetricsServiceRequest{}
	// Test CopyTo empty
	dest = CopyLazyExportMetricsServiceRequestPtrSlice(dest, src)
	assert.Equal(t, []*LazyExportMetricsServiceRequest{}, dest)

	// Test CopyTo larger slice
	src = GenTestLazyExportMetricsServiceRequestPtrSlice()
	dest = CopyLazyExportMetricsServiceRequestPtrSlice(dest, src)
	assert.Equal(t, GenTestLazyExportMetricsServiceRequestPtrSlice(), dest)

	// Test CopyTo same size slice
	dest = CopyLazyExportMetricsServiceRequestPtrSlice(dest, src)
	assert.Equal(t, GenTestLazyExportMetricsServiceRequestPtrSlice(), dest)

	// Test CopyTo smaller size slice
	dest = CopyLazyExportMetricsServiceRequestPtrSlice(dest, []*LazyExportMetricsServiceRequest{})
	assert.Len(t, dest, 0)

	// Test CopyTo larger slice with enough capacity
	dest = CopyLazyExportMetricsServiceRequestPtrSlice(dest, src)
	assert.Equal(t, GenTestLazyExportMetricsServiceRequestPtrSlice(), dest)
}

func TestMarshalAndUnmarshalJSONLazyExportMetricsServiceRequestUnknown(t *testing.T) {
	iter := json.BorrowIterator([]byte(`{"unknown": "string"}`))
	defer json.ReturnIterator(iter)
	dest := NewLazyExportMetricsServiceRequest()
	dest.UnmarshalJSON(iter)
	require.NoError(t, iter.Error())
	assert.Equal(t, NewLazyExportMetricsServiceRequest(), dest)
}

func TestMarshalAndUnmarshalJSONLazyExportMetricsServiceRequest(t *testing.T) {
	for name, src := range genTestEncodingValuesLazyExportMetricsServiceRequest() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				stream := json.BorrowStream(nil)
				defer json.ReturnStream(stream)
				src.MarshalJSON(stream)
				require.NoError(t, stream.Error())

				iter := json.BorrowIterator(stream.Buffer())
				defer json.ReturnIterator(iter)
				dest := NewLazyExportMetricsServiceRequest()
				dest.UnmarshalJSON(iter)
				require.NoError(t, iter.Error())

				assert.Equal(t, src, dest)
				DeleteLazyExportMetricsServiceRequest(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoLazyExportMetricsServiceRequestFailing(t *testing.T) {
	for name, buf := range genTestFailingUnmarshalProtoValuesLazyExportMetricsServiceRequest() {
		t.Run(name, func(t *testing.T) {
			dest := NewLazyExportMetricsServiceRequest()
			require.Error(t, dest.UnmarshalProto(buf))
		})
	}
}

func TestMarshalAndUnmarshalProtoLazyExportMetricsServiceRequestUnknown(t *testing.T) {
	dest := NewLazyExportMetricsServiceRequest()
	// message Test { required int64 field = 1313; } encoding { "field": "1234" }
	require.NoError(t, dest.UnmarshalProto([]byte{0x88, 0x52, 0xD2, 0x09}))
	assert.Equal(t, NewLazyExportMetricsServiceRequest(), dest)
}

func TestMarshalAndUnmarshalProtoLazyExportMetricsServiceRequest(t *testing.T) {
	for name, src := range genTestEncodingValuesLazyExportMetricsServiceRequest() {
		for _, pooling := range []bool{true, false} {
			t.Run(name+"/Pooling="+strconv.FormatBool(pooling), func(t *testing.T) {
				prevPooling := UseProtoPooling.IsEnabled()
				require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), pooling))
				defer func() {
					require.NoError(t, featuregate.GlobalRegistry().Set(UseProtoPooling.ID(), prevPooling))
				}()

				buf := make([]byte, src.SizeProto())
				gotSize := src.MarshalProto(buf)
				assert.Equal(t, len(buf), gotSize)

				dest := NewLazyExportMetricsServiceRequest()
				require.NoError(t, dest.UnmarshalProto(buf))

				assert.Equal(t, src, dest)
				DeleteLazyExportMetricsServiceRequest(dest, true)
			})
		}
	}
}

func TestMarshalAndUnmarshalProtoViaProtobufLazyExportMetricsServiceRequest(t *testing.T) {
	for name, src := range genTestEncodingValuesLazyExportMetricsServiceRequest() {
		t.Run(name, func(t *testing.T) {
			buf := make([]byte, src.SizeProto())
			gotSize := src.MarshalProto(buf)
			assert.Equal(t, len(buf), gotSize)

			goDest := &gootlpcollectormetrics.LazyExportMetricsServiceRequest{}
			require.NoError(t, proto.Unmarshal(buf, goDest))

			goBuf, err := proto.Marshal(goDest)
			require.NoError(t, err)

			dest := NewLazyExportMetricsServiceRequest()
			require.NoError(t, dest.UnmarshalProto(goBuf))
			assert.Equal(t, src, dest)
		})
	}
}

func genTestFailingUnmarshalProtoValuesLazyExportMetricsServiceRequest() map[string][]byte {
	return map[string][]byte{
		"invalid_field":                   {0x02},
		"ResourceMetrics/wrong_wire_type": {0xc},
		"ResourceMetrics/missing_value":   {0xa},
	}
}

func genTestEncodingValuesLazyExportMetricsServiceRequest() map[string]*LazyExportMetricsServiceRequest {
	return map[string]*LazyExportMetricsServiceRequest{
		"empty":                NewLazyExportMetricsServiceRequest(),
		"ResourceMetrics/test": {ResourceMetrics: [][]byte{nil, {1, 2, 3}}},
	}
}
