// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package internal

type LazyMetricsWrapper struct {
	orig  *LazyExportMetricsServiceRequest
	state *State
}

func GetLazyMetricsOrig(ms LazyMetricsWrapper) *LazyExportMetricsServiceRequest {
	return ms.orig
}

func GetLazyMetricsState(ms LazyMetricsWrapper) *State {
	return ms.state
}

func NewLazyMetricsWrapper(orig *LazyExportMetricsServiceRequest, state *State) LazyMetricsWrapper {
	return LazyMetricsWrapper{orig: orig, state: state}
}

func GenTestLazyMetricsWrapper() LazyMetricsWrapper {
	return NewLazyMetricsWrapper(GenTestLazyExportMetricsServiceRequest(), NewState())
}
