// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package ptrace

import (
	"slices"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceSpans is a collection of spans from a Resource.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewResourceSpans function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ResourceSpans struct {
	orig  *internal.ResourceSpans
	state *internal.State
}

func newResourceSpans(orig *internal.ResourceSpans, state *internal.State) ResourceSpans {
	return ResourceSpans{orig: orig, state: state}
}

// NewResourceSpans creates a new empty ResourceSpans.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewResourceSpans() ResourceSpans {
	return newResourceSpans(internal.NewResourceSpans(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms ResourceSpans) MoveTo(dest ResourceSpans) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.orig == dest.orig {
		return
	}
	internal.DeleteResourceSpans(dest.orig, false)
	*dest.orig, *ms.orig = *ms.orig, *dest.orig
}

// Resource returns the resource associated with this ResourceSpans.
func (ms ResourceSpans) Resource() pcommon.Resource {
	return pcommon.Resource(internal.NewResourceWrapper(&ms.orig.Resource, ms.state))
}

// ScopeSpans returns the ScopeSpans associated with this ResourceSpans.
func (ms ResourceSpans) ScopeSpans() ScopeSpansSlice {
	return newScopeSpansSlice(&ms.orig.ScopeSpans, ms.state)
}

// SchemaUrl returns the schemaurl associated with this ResourceSpans.
func (ms ResourceSpans) SchemaUrl() string {
	return ms.orig.SchemaUrl
}

// SetSchemaUrl replaces the schemaurl associated with this ResourceSpans.
func (ms ResourceSpans) SetSchemaUrl(v string) {
	ms.state.AssertMutable()
	ms.orig.SchemaUrl = v
}

// MarshalProto marshals ResourceSpans into proto bytes.
func (ms ResourceSpans) MarshalProto() ([]byte, error) {
	orig := ms.orig
	size := orig.SizeProto()
	buf := make([]byte, size)
	_ = orig.MarshalProto(buf)
	return buf, nil
}

// UnmarshalProto unmarshalls ResourceSpans from proto bytes.
func (ms ResourceSpans) UnmarshalProto(data []byte) error {
	orig := ms.orig
	err := orig.UnmarshalProto(data)
	if err != nil {
		return err
	}
	return nil
}

// MarshalJSON marshals ResourceSpans into JSON bytes.
func (ms ResourceSpans) MarshalJSON() ([]byte, error) {
	orig := ms.orig
	dest := json.BorrowStream(nil)
	defer json.ReturnStream(dest)
	orig.MarshalJSON(dest)
	if dest.Error() != nil {
		return nil, dest.Error()
	}
	return slices.Clone(dest.Buffer()), nil
}

// UnmarshalJSON unmarshalls ResourceSpans from JSON bytes.
func (ms ResourceSpans) UnmarshalJSON(data []byte) error {
	orig := ms.orig
	iter := json.BorrowIterator(data)
	defer json.ReturnIterator(iter)
	orig.UnmarshalJSON(iter)
	return iter.Error()
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms ResourceSpans) CopyTo(dest ResourceSpans) {
	dest.state.AssertMutable()
	internal.CopyResourceSpans(dest.orig, ms.orig)
}
