// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pprofile

import (
	"slices"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

// ValueType describes the type and units of a value.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewValueType function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ValueType struct {
	orig  *internal.ValueType
	state *internal.State
}

func newValueType(orig *internal.ValueType, state *internal.State) ValueType {
	return ValueType{orig: orig, state: state}
}

// NewValueType creates a new empty ValueType.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewValueType() ValueType {
	return newValueType(internal.NewValueType(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms ValueType) MoveTo(dest ValueType) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.orig == dest.orig {
		return
	}
	internal.DeleteValueType(dest.orig, false)
	*dest.orig, *ms.orig = *ms.orig, *dest.orig
}

// TypeStrindex returns the typestrindex associated with this ValueType.
func (ms ValueType) TypeStrindex() int32 {
	return ms.orig.TypeStrindex
}

// SetTypeStrindex replaces the typestrindex associated with this ValueType.
func (ms ValueType) SetTypeStrindex(v int32) {
	ms.state.AssertMutable()
	ms.orig.TypeStrindex = v
}

// UnitStrindex returns the unitstrindex associated with this ValueType.
func (ms ValueType) UnitStrindex() int32 {
	return ms.orig.UnitStrindex
}

// SetUnitStrindex replaces the unitstrindex associated with this ValueType.
func (ms ValueType) SetUnitStrindex(v int32) {
	ms.state.AssertMutable()
	ms.orig.UnitStrindex = v
}

// MarshalProto marshals ValueType into proto bytes.
func (ms ValueType) MarshalProto() ([]byte, error) {
	orig := ms.orig
	size := orig.SizeProto()
	buf := make([]byte, size)
	_ = orig.MarshalProto(buf)
	return buf, nil
}

// UnmarshalProto unmarshalls ValueType from proto bytes.
func (ms ValueType) UnmarshalProto(data []byte) error {
	orig := ms.orig
	err := orig.UnmarshalProto(data)
	if err != nil {
		return err
	}
	return nil
}

// MarshalJSON marshals ValueType into JSON bytes.
func (ms ValueType) MarshalJSON() ([]byte, error) {
	orig := ms.orig
	dest := json.BorrowStream(nil)
	defer json.ReturnStream(dest)
	orig.MarshalJSON(dest)
	if dest.Error() != nil {
		return nil, dest.Error()
	}
	return slices.Clone(dest.Buffer()), nil
}

// UnmarshalJSON unmarshalls ValueType from JSON bytes.
func (ms ValueType) UnmarshalJSON(data []byte) error {
	orig := ms.orig
	iter := json.BorrowIterator(data)
	defer json.ReturnIterator(iter)
	orig.UnmarshalJSON(iter)
	return iter.Error()
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms ValueType) CopyTo(dest ValueType) {
	dest.state.AssertMutable()
	internal.CopyValueType(dest.orig, ms.orig)
}
