// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"slices"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceMetrics is a collection of metrics from a Resource.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewLazyResourceMetrics function to create new instances.
// Important: zero-initialized instance is not valid for use.
type LazyResourceMetrics struct {
	orig  *internal.LazyResourceMetrics
	state *internal.State
}

func newLazyResourceMetrics(orig *internal.LazyResourceMetrics, state *internal.State) LazyResourceMetrics {
	return LazyResourceMetrics{orig: orig, state: state}
}

// NewLazyResourceMetrics creates a new empty LazyResourceMetrics.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewLazyResourceMetrics() LazyResourceMetrics {
	return newLazyResourceMetrics(internal.NewLazyResourceMetrics(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms LazyResourceMetrics) MoveTo(dest LazyResourceMetrics) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.orig == dest.orig {
		return
	}
	internal.DeleteLazyResourceMetrics(dest.orig, false)
	*dest.orig, *ms.orig = *ms.orig, *dest.orig
}

// Resource returns the resource associated with this LazyResourceMetrics.
func (ms LazyResourceMetrics) Resource() pcommon.Resource {
	return pcommon.Resource(internal.NewResourceWrapper(&ms.orig.Resource, ms.state))
}

// ScopeMetrics returns the ScopeMetrics associated with this LazyResourceMetrics.
func (ms LazyResourceMetrics) ScopeMetrics() pcommon.BytesSlice {
	return pcommon.BytesSlice(internal.NewBytesSliceWrapper(&ms.orig.ScopeMetrics, ms.state))
}

// SchemaUrl returns the schemaurl associated with this LazyResourceMetrics.
func (ms LazyResourceMetrics) SchemaUrl() string {
	return ms.orig.SchemaUrl
}

// SetSchemaUrl replaces the schemaurl associated with this LazyResourceMetrics.
func (ms LazyResourceMetrics) SetSchemaUrl(v string) {
	ms.state.AssertMutable()
	ms.orig.SchemaUrl = v
}

// MarshalProto marshals LazyResourceMetrics into proto bytes.
func (ms LazyResourceMetrics) MarshalProto() ([]byte, error) {
	orig := ms.orig
	size := orig.SizeProto()
	buf := make([]byte, size)
	_ = orig.MarshalProto(buf)
	return buf, nil
}

// UnmarshalProto unmarshalls LazyResourceMetrics from proto bytes.
func (ms LazyResourceMetrics) UnmarshalProto(data []byte) error {
	orig := ms.orig
	err := orig.UnmarshalProto(data)
	if err != nil {
		return err
	}
	return nil
}

// MarshalJSON marshals LazyResourceMetrics into JSON bytes.
func (ms LazyResourceMetrics) MarshalJSON() ([]byte, error) {
	orig := ms.orig
	dest := json.BorrowStream(nil)
	defer json.ReturnStream(dest)
	orig.MarshalJSON(dest)
	if dest.Error() != nil {
		return nil, dest.Error()
	}
	return slices.Clone(dest.Buffer()), nil
}

// UnmarshalJSON unmarshalls LazyResourceMetrics from JSON bytes.
func (ms LazyResourceMetrics) UnmarshalJSON(data []byte) error {
	orig := ms.orig
	iter := json.BorrowIterator(data)
	defer json.ReturnIterator(iter)
	orig.UnmarshalJSON(iter)
	return iter.Error()
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms LazyResourceMetrics) CopyTo(dest LazyResourceMetrics) {
	dest.state.AssertMutable()
	internal.CopyLazyResourceMetrics(dest.orig, ms.orig)
}
