// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"slices"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/json"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// LazyMetrics is the top-level struct that is propagated through the metrics pipeline.
// Use NewLazyMetrics to create new instance, zero-initialized instance is not valid for use.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewLazyMetrics function to create new instances.
// Important: zero-initialized instance is not valid for use.
type LazyMetrics internal.LazyMetricsWrapper

func newLazyMetrics(orig *internal.LazyExportMetricsServiceRequest, state *internal.State) LazyMetrics {
	return LazyMetrics(internal.NewLazyMetricsWrapper(orig, state))
}

// NewLazyMetrics creates a new empty LazyMetrics.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewLazyMetrics() LazyMetrics {
	return newLazyMetrics(internal.NewLazyExportMetricsServiceRequest(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms LazyMetrics) MoveTo(dest LazyMetrics) {
	ms.getState().AssertMutable()
	dest.getState().AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.getOrig() == dest.getOrig() {
		return
	}
	internal.DeleteLazyExportMetricsServiceRequest(dest.getOrig(), false)
	*dest.getOrig(), *ms.getOrig() = *ms.getOrig(), *dest.getOrig()
}

// ResourceMetrics returns the ResourceMetrics associated with this LazyMetrics.
func (ms LazyMetrics) ResourceMetrics() pcommon.BytesSlice {
	return pcommon.BytesSlice(internal.NewBytesSliceWrapper(&ms.getOrig().ResourceMetrics, ms.getState()))
}

// MarshalProto marshals LazyMetrics into proto bytes.
func (ms LazyMetrics) MarshalProto() ([]byte, error) {
	orig := ms.getOrig()
	size := orig.SizeProto()
	buf := make([]byte, size)
	_ = orig.MarshalProto(buf)
	return buf, nil
}

// UnmarshalProto unmarshalls LazyMetrics from proto bytes.
func (ms LazyMetrics) UnmarshalProto(data []byte) error {
	orig := ms.getOrig()
	err := orig.UnmarshalProto(data)
	if err != nil {
		return err
	}
	return nil
}

// MarshalJSON marshals LazyMetrics into JSON bytes.
func (ms LazyMetrics) MarshalJSON() ([]byte, error) {
	orig := ms.getOrig()
	dest := json.BorrowStream(nil)
	defer json.ReturnStream(dest)
	orig.MarshalJSON(dest)
	if dest.Error() != nil {
		return nil, dest.Error()
	}
	return slices.Clone(dest.Buffer()), nil
}

// UnmarshalJSON unmarshalls LazyMetrics from JSON bytes.
func (ms LazyMetrics) UnmarshalJSON(data []byte) error {
	orig := ms.getOrig()
	iter := json.BorrowIterator(data)
	defer json.ReturnIterator(iter)
	orig.UnmarshalJSON(iter)
	return iter.Error()
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms LazyMetrics) CopyTo(dest LazyMetrics) {
	dest.getState().AssertMutable()
	internal.CopyLazyExportMetricsServiceRequest(dest.getOrig(), ms.getOrig())
}

func (ms LazyMetrics) getOrig() *internal.LazyExportMetricsServiceRequest {
	return internal.GetLazyMetricsOrig(internal.LazyMetricsWrapper(ms))
}

func (ms LazyMetrics) getState() *internal.State {
	return internal.GetLazyMetricsState(internal.LazyMetricsWrapper(ms))
}
