// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

func TestLazyResourceMetrics_MoveTo(t *testing.T) {
	ms := generateTestLazyResourceMetrics()
	dest := NewLazyResourceMetrics()
	ms.MoveTo(dest)
	assert.Equal(t, NewLazyResourceMetrics(), ms)
	assert.Equal(t, generateTestLazyResourceMetrics(), dest)
	dest.MoveTo(dest)
	assert.Equal(t, generateTestLazyResourceMetrics(), dest)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newLazyResourceMetrics(internal.NewLazyResourceMetrics(), sharedState)) })
	assert.Panics(t, func() { newLazyResourceMetrics(internal.NewLazyResourceMetrics(), sharedState).MoveTo(dest) })
}

func TestLazyResourceMetrics_CopyTo(t *testing.T) {
	ms := NewLazyResourceMetrics()
	orig := NewLazyResourceMetrics()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	orig = generateTestLazyResourceMetrics()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newLazyResourceMetrics(internal.NewLazyResourceMetrics(), sharedState)) })
}

func TestLazyResourceMetrics_Resource(t *testing.T) {
	ms := NewLazyResourceMetrics()
	assert.Equal(t, pcommon.NewResource(), ms.Resource())
	ms.orig.Resource = *internal.GenTestResource()
	assert.Equal(t, pcommon.Resource(internal.GenTestResourceWrapper()), ms.Resource())
}

func TestLazyResourceMetrics_ScopeMetrics(t *testing.T) {
	ms := NewLazyResourceMetrics()
	assert.Equal(t, pcommon.NewBytesSlice(), ms.ScopeMetrics())
	ms.orig.ScopeMetrics = internal.GenTestBytesSlice()
	assert.Equal(t, pcommon.BytesSlice(internal.GenTestBytesSliceWrapper()), ms.ScopeMetrics())
}

func TestLazyResourceMetrics_SchemaUrl(t *testing.T) {
	ms := NewLazyResourceMetrics()
	assert.Empty(t, ms.SchemaUrl())
	ms.SetSchemaUrl("test_schemaurl")
	assert.Equal(t, "test_schemaurl", ms.SchemaUrl())
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() {
		newLazyResourceMetrics(internal.NewLazyResourceMetrics(), sharedState).SetSchemaUrl("test_schemaurl")
	})
}

func generateTestLazyResourceMetrics() LazyResourceMetrics {
	return newLazyResourceMetrics(internal.GenTestLazyResourceMetrics(), internal.NewState())
}
