// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pmetric

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

func TestLazyMetrics_MoveTo(t *testing.T) {
	ms := generateTestLazyMetrics()
	dest := NewLazyMetrics()
	ms.MoveTo(dest)
	assert.Equal(t, NewLazyMetrics(), ms)
	assert.Equal(t, generateTestLazyMetrics(), dest)
	dest.MoveTo(dest)
	assert.Equal(t, generateTestLazyMetrics(), dest)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.MoveTo(newLazyMetrics(internal.NewLazyExportMetricsServiceRequest(), sharedState)) })
	assert.Panics(t, func() { newLazyMetrics(internal.NewLazyExportMetricsServiceRequest(), sharedState).MoveTo(dest) })
}

func TestLazyMetrics_CopyTo(t *testing.T) {
	ms := NewLazyMetrics()
	orig := NewLazyMetrics()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	orig = generateTestLazyMetrics()
	orig.CopyTo(ms)
	assert.Equal(t, orig, ms)
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	assert.Panics(t, func() { ms.CopyTo(newLazyMetrics(internal.NewLazyExportMetricsServiceRequest(), sharedState)) })
}

func TestLazyMetrics_ResourceMetrics(t *testing.T) {
	ms := NewLazyMetrics()
	assert.Equal(t, pcommon.NewBytesSlice(), ms.ResourceMetrics())
	ms.getOrig().ResourceMetrics = internal.GenTestBytesSlice()
	assert.Equal(t, pcommon.BytesSlice(internal.GenTestBytesSliceWrapper()), ms.ResourceMetrics())
}

func generateTestLazyMetrics() LazyMetrics {
	return newLazyMetrics(internal.GenTestLazyExportMetricsServiceRequest(), internal.NewState())
}
