// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pcommon

import (
	"iter"

	"go.opentelemetry.io/collector/pdata/internal"
)

// BytesSlice represents a [][]byte slice.
// The instance of BytesSlice can be assigned to multiple objects since it's immutable.
//
// Must use NewBytesSlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type BytesSlice internal.BytesSliceWrapper

func (ms BytesSlice) getOrig() *[][]byte {
	return internal.GetBytesSliceOrig(internal.BytesSliceWrapper(ms))
}

func (ms BytesSlice) getState() *internal.State {
	return internal.GetBytesSliceState(internal.BytesSliceWrapper(ms))
}

// NewBytesSlice creates a new empty BytesSlice.
func NewBytesSlice() BytesSlice {
	orig := [][]byte(nil)
	return BytesSlice(internal.NewBytesSliceWrapper(&orig, internal.NewState()))
}

// AsRaw returns a copy of the [][]byte slice.
func (ms BytesSlice) AsRaw() [][]byte {
	return copyBytesSlice(nil, *ms.getOrig())
}

// FromRaw copies raw [][]byte into the slice BytesSlice.
func (ms BytesSlice) FromRaw(val [][]byte) {
	ms.getState().AssertMutable()
	*ms.getOrig() = copyBytesSlice(*ms.getOrig(), val)
}

// Len returns length of the [][]byte slice value.
// Equivalent of len(bytesSlice).
func (ms BytesSlice) Len() int {
	return len(*ms.getOrig())
}

// At returns an item from particular index.
// Equivalent of bytesSlice[i].
func (ms BytesSlice) At(i int) []byte {
	return (*ms.getOrig())[i]
}

// All returns an iterator over index-value pairs in the slice.
func (ms BytesSlice) All() iter.Seq2[int, []byte] {
	return func(yield func(int, []byte) bool) {
		for i := 0; i < ms.Len(); i++ {
			if !yield(i, ms.At(i)) {
				return
			}
		}
	}
}

// SetAt sets []byte item at particular index.
// Equivalent of bytesSlice[i] = val
func (ms BytesSlice) SetAt(i int, val []byte) {
	ms.getState().AssertMutable()
	(*ms.getOrig())[i] = val
}

// EnsureCapacity ensures BytesSlice has at least the specified capacity.
//  1. If the newCap <= cap, then is no change in capacity.
//  2. If the newCap > cap, then the slice capacity will be expanded to the provided value which will be equivalent of:
//     buf := make([][]byte, len(bytesSlice), newCap)
//     copy(buf, bytesSlice)
//     bytesSlice = buf
func (ms BytesSlice) EnsureCapacity(newCap int) {
	ms.getState().AssertMutable()
	oldCap := cap(*ms.getOrig())
	if newCap <= oldCap {
		return
	}

	newOrig := make([][]byte, len(*ms.getOrig()), newCap)
	copy(newOrig, *ms.getOrig())
	*ms.getOrig() = newOrig
}

// Append appends extra elements to BytesSlice.
// Equivalent of bytesSlice = append(bytesSlice, elms...)
func (ms BytesSlice) Append(elms ...[]byte) {
	ms.getState().AssertMutable()
	*ms.getOrig() = append(*ms.getOrig(), elms...)
}

// MoveTo moves all elements from the current slice overriding the destination and
// resetting the current instance to its zero value.
func (ms BytesSlice) MoveTo(dest BytesSlice) {
	ms.getState().AssertMutable()
	dest.getState().AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.getOrig() == dest.getOrig() {
		return
	}
	*dest.getOrig() = *ms.getOrig()
	*ms.getOrig() = nil
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (ms BytesSlice) MoveAndAppendTo(dest BytesSlice) {
	ms.getState().AssertMutable()
	dest.getState().AssertMutable()
	if *dest.getOrig() == nil {
		// We can simply move the entire vector and avoid any allocations.
		*dest.getOrig() = *ms.getOrig()
	} else {
		*dest.getOrig() = append(*dest.getOrig(), *ms.getOrig()...)
	}
	*ms.getOrig() = nil
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (ms BytesSlice) RemoveIf(f func([]byte) bool) {
	ms.getState().AssertMutable()
	newLen := 0
	for i := 0; i < len(*ms.getOrig()); i++ {
		if f((*ms.getOrig())[i]) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		(*ms.getOrig())[newLen] = (*ms.getOrig())[i]
		var zero []byte
		(*ms.getOrig())[i] = zero
		newLen++
	}
	*ms.getOrig() = (*ms.getOrig())[:newLen]
}

// CopyTo copies all elements from the current slice overriding the destination.
func (ms BytesSlice) CopyTo(dest BytesSlice) {
	dest.getState().AssertMutable()
	if ms.getOrig() == dest.getOrig() {
		return
	}
	*dest.getOrig() = copyBytesSlice(*dest.getOrig(), *ms.getOrig())
}

func copyBytesSlice(dst, src [][]byte) [][]byte {
	return append(dst[:0], src...)
}
