// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pcommon

import (
	"slices"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/json"
)

// Resource is a message representing the resource information.
//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewResource function to create new instances.
// Important: zero-initialized instance is not valid for use.
type Resource internal.ResourceWrapper

func newResource(orig *internal.Resource, state *internal.State) Resource {
	return Resource(internal.NewResourceWrapper(orig, state))
}

// NewResource creates a new empty Resource.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewResource() Resource {
	return newResource(internal.NewResource(), internal.NewState())
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms Resource) MoveTo(dest Resource) {
	ms.getState().AssertMutable()
	dest.getState().AssertMutable()
	// If they point to the same data, they are the same, nothing to do.
	if ms.getOrig() == dest.getOrig() {
		return
	}
	internal.DeleteResource(dest.getOrig(), false)
	*dest.getOrig(), *ms.getOrig() = *ms.getOrig(), *dest.getOrig()
}

// Attributes returns the Attributes associated with this Resource.
func (ms Resource) Attributes() Map {
	return Map(internal.NewMapWrapper(&ms.getOrig().Attributes, ms.getState()))
}

// DroppedAttributesCount returns the droppedattributescount associated with this Resource.
func (ms Resource) DroppedAttributesCount() uint32 {
	return ms.getOrig().DroppedAttributesCount
}

// SetDroppedAttributesCount replaces the droppedattributescount associated with this Resource.
func (ms Resource) SetDroppedAttributesCount(v uint32) {
	ms.getState().AssertMutable()
	ms.getOrig().DroppedAttributesCount = v
}

// MarshalProto marshals Resource into proto bytes.
func (ms Resource) MarshalProto() ([]byte, error) {
	orig := ms.getOrig()
	size := orig.SizeProto()
	buf := make([]byte, size)
	_ = orig.MarshalProto(buf)
	return buf, nil
}

// UnmarshalProto unmarshalls Resource from proto bytes.
func (ms Resource) UnmarshalProto(data []byte) error {
	orig := ms.getOrig()
	err := orig.UnmarshalProto(data)
	if err != nil {
		return err
	}
	return nil
}

// MarshalJSON marshals Resource into JSON bytes.
func (ms Resource) MarshalJSON() ([]byte, error) {
	orig := ms.getOrig()
	dest := json.BorrowStream(nil)
	defer json.ReturnStream(dest)
	orig.MarshalJSON(dest)
	if dest.Error() != nil {
		return nil, dest.Error()
	}
	return slices.Clone(dest.Buffer()), nil
}

// UnmarshalJSON unmarshalls Resource from JSON bytes.
func (ms Resource) UnmarshalJSON(data []byte) error {
	orig := ms.getOrig()
	iter := json.BorrowIterator(data)
	defer json.ReturnIterator(iter)
	orig.UnmarshalJSON(iter)
	return iter.Error()
}

// CopyTo copies all properties from the current struct overriding the destination.
func (ms Resource) CopyTo(dest Resource) {
	dest.getState().AssertMutable()
	internal.CopyResource(dest.getOrig(), ms.getOrig())
}

func (ms Resource) getOrig() *internal.Resource {
	return internal.GetResourceOrig(internal.ResourceWrapper(ms))
}

func (ms Resource) getState() *internal.State {
	return internal.GetResourceState(internal.ResourceWrapper(ms))
}
