// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pcommon

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
)

func TestNewBytesSlice(t *testing.T) {
	ms := NewBytesSlice()
	assert.Equal(t, 0, ms.Len())
	ms.FromRaw([][]byte{{1}, {2}, {3}})
	assert.Equal(t, 3, ms.Len())
	assert.Equal(t, [][]byte{{1}, {2}, {3}}, ms.AsRaw())
	ms.SetAt(1, []byte([]byte{4}))
	assert.Equal(t, [][]byte{{1}, {4}, {3}}, ms.AsRaw())
	ms.FromRaw([][]byte{{3}})
	assert.Equal(t, 1, ms.Len())
	assert.Equal(t, []byte([]byte{3}), ms.At(0))

	cp := NewBytesSlice()
	ms.CopyTo(cp)
	ms.SetAt(0, []byte([]byte{2}))
	assert.Equal(t, []byte([]byte{2}), ms.At(0))
	assert.Equal(t, []byte([]byte{3}), cp.At(0))
	ms.CopyTo(cp)
	assert.Equal(t, []byte([]byte{2}), cp.At(0))

	mv := NewBytesSlice()
	ms.MoveTo(mv)
	assert.Equal(t, 0, ms.Len())
	assert.Equal(t, 1, mv.Len())
	assert.Equal(t, []byte([]byte{2}), mv.At(0))
	ms.FromRaw([][]byte{{1}, {2}, {3}})
	ms.MoveTo(mv)
	assert.Equal(t, 3, mv.Len())
	assert.Equal(t, []byte([]byte{1}), mv.At(0))
	mv.MoveTo(mv)
	assert.Equal(t, 3, mv.Len())
	assert.Equal(t, []byte([]byte{1}), mv.At(0))
}

func TestBytesSliceReadOnly(t *testing.T) {
	raw := [][]byte{{1}, {2}, {3}}
	sharedState := internal.NewState()
	sharedState.MarkReadOnly()
	ms := BytesSlice(internal.NewBytesSliceWrapper(&raw, sharedState))

	assert.Equal(t, 3, ms.Len())
	assert.Equal(t, []byte([]byte{1}), ms.At(0))
	assert.Panics(t, func() { ms.Append([]byte{1}) })
	assert.Panics(t, func() { ms.EnsureCapacity(2) })
	assert.Equal(t, raw, ms.AsRaw())
	assert.Panics(t, func() { ms.FromRaw(raw) })

	ms2 := NewBytesSlice()
	ms.CopyTo(ms2)
	assert.Equal(t, ms.AsRaw(), ms2.AsRaw())
	assert.Panics(t, func() { ms2.CopyTo(ms) })

	assert.Panics(t, func() { ms.MoveTo(ms2) })
	assert.Panics(t, func() { ms2.MoveTo(ms) })
}

func TestBytesSliceAppend(t *testing.T) {
	ms := NewBytesSlice()
	ms.FromRaw([][]byte{{1}, {2}, {3}})
	ms.Append([]byte{4}, []byte{4})
	assert.Equal(t, 5, ms.Len())
	assert.Equal(t, []byte([]byte{4}), ms.At(4))
}

func TestBytesSliceEnsureCapacity(t *testing.T) {
	ms := NewBytesSlice()
	ms.EnsureCapacity(4)
	assert.Equal(t, 4, cap(*ms.getOrig()))
	ms.EnsureCapacity(2)
	assert.Equal(t, 4, cap(*ms.getOrig()))
}

func TestBytesSliceAll(t *testing.T) {
	ms := NewBytesSlice()
	ms.FromRaw([][]byte{{1}, {2}, {3}})
	assert.NotEmpty(t, ms.Len())

	var c int
	for i, v := range ms.All() {
		assert.Equal(t, ms.At(i), v, "element should match")
		c++
	}
	assert.Equal(t, ms.Len(), c, "All elements should have been visited")
}

func TestBytesSliceMoveAndAppendTo(t *testing.T) {
	// Test moving from an empty slice
	ms := NewBytesSlice()
	ms2 := NewBytesSlice()
	ms.MoveAndAppendTo(ms2)
	assert.Equal(t, NewBytesSlice(), ms2)
	assert.Equal(t, ms.Len(), 0)

	// Test moving to empty slice
	ms.FromRaw([][]byte{{1}, {2}, {3}})
	ms.MoveAndAppendTo(ms2)
	assert.Equal(t, ms2.Len(), 3)

	// Test moving to a non empty slice
	ms.FromRaw([][]byte{{1}, {2}, {3}})
	ms.MoveAndAppendTo(ms2)
	assert.Equal(t, ms2.Len(), 6)
}

func TestBytesSliceRemoveIf(t *testing.T) {
	emptySlice := NewBytesSlice()
	emptySlice.RemoveIf(func(el []byte) bool {
		t.Fail()
		return false
	})

	ms := NewBytesSlice()
	ms.FromRaw([][]byte{{1}, {2}, {3}})
	pos := 0
	ms.RemoveIf(func(el []byte) bool {
		pos++
		return pos%2 == 1
	})
	assert.Equal(t, pos/2, ms.Len())
}

func TestBytesSliceRemoveIfAll(t *testing.T) {
	ms := NewBytesSlice()
	ms.FromRaw([][]byte{{1}, {2}, {3}})
	ms.RemoveIf(func(el []byte) bool {
		return true
	})
	assert.Equal(t, 0, ms.Len())
}

func TestBytesSliceEqual(t *testing.T) {
	ms := NewBytesSlice()
	ms2 := NewBytesSlice()
	assert.True(t, ms.Equal(ms2))

	ms.Append([]byte{1}, []byte{2}, []byte{3})
	assert.False(t, ms.Equal(ms2))

	ms2.Append([]byte{1}, []byte{2}, []byte{3})
	assert.True(t, ms.Equal(ms2))
}

func BenchmarkBytesSliceEqual(b *testing.B) {
	ms := NewBytesSlice()
	ms.Append([]byte{1}, []byte{2}, []byte{3})
	cmp := NewBytesSlice()
	cmp.Append([]byte{1}, []byte{2}, []byte{3})

	b.ResetTimer()
	b.ReportAllocs()

	for n := 0; n < b.N; n++ {
		_ = ms.Equal(cmp)
	}
}
